version: '3.8'
services:
  imex-app-fastapi:
    build: .
    ports:` 
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
      - ./main.py:/app/main.py
    # Để tự động reload khi code thay đổi trong lúc phát triển
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
